---
- name: Install VIM
  become: yes
  apt:
    pkg: vim
    state: "{{ vim_package_state }}"
    update_cache: yes
    cache_valid_time: 3600

- name: Set VIM as default editor
  become: yes
  alternatives:
    name: editor
    path: /usr/bin/vim.basic
