---
- name: VIM | Install VIM
  sudo: yes
  apt:
    pkg: vim
    state: "{{ base_packages_state }}"
    update_cache: yes
    cache_valid_time: 3600

- name: VIM | Set VIM as default editor
  sudo: yes
  alternatives:
    name: editor
    path: /usr/bin/vim.basic
